extension = pdfconverter
version = 5.0.0
source = src
target = packageparts

; Create a pre-release of the extension on GitHub
; Add your personal GitHub access token
; and add Release to the target (separated by space) above
[github]
remote = origin
branch = develop
token =
owner = flygcert
repository = plg-pdfconverter
changelog_source = commits

; Automatic upload of the built extension package to an FTP server
[ftp]
host =
port = 21
user =
password =
ssl = false
target = /

[build]
vendor_exclude =
	**/vendor/**/.*.yml
	**/vendor/**/.editor*
	**/vendor/**/.github/
	**/vendor/**/.mailmap
	**/vendor/**/.php_cs*
	**/vendor/**/*.md
	**/vendor/**/*.rst
	**/vendor/**/*.sh
	**/vendor/**/bin/
	**/vendor/**/CHANGELOG*
	**/vendor/**/CREDITS*
	**/vendor/**/doc/
	**/vendor/**/docker-compose.yml
	**/vendor/**/Dockerfile
	**/vendor/**/docs/
	**/vendor/**/examples/
	**/vendor/**/ext/
	**/vendor/**/LICENSE*
	**/vendor/**/Makefile
	**/vendor/**/phpcs.xml*
	**/vendor/**/phpdoc.xml
	**/vendor/**/phpdocs-md
	**/vendor/**/phpstan.neon.dist
	**/vendor/**/phpstan-baseline.neon
	**/vendor/**/phpstan.neon
	**/vendor/**/phpunit-nocover.xml
	**/vendor/**/phpunit.xml*
	**/vendor/**/readme.txt
	**/vendor/**/rector.yaml
	**/vendor/**/site/
	**/vendor/**/test/
	**/vendor/**/tests/
	**/vendor/**/Tests/
	**/vendor/**/todo
	**/vendor/**/ttfonts

; Adds / replaces copyright headers at the beginning of files in the source folder
[header]
files = php,js
text = "
/**
 * @package     Data Sync
 *
 * @copyright   (C) 2007 - ##YEAR## Flygcert FZE. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */
"
